export const ITEMS = [
    { id: "1", name: "Cicero", bank: "Itaú", selected: false },
    { id: "2", name: "Marcelia", bank: "Bradesco", selected: false },
    { id: "3", name: "Marcelia", bank: "Itaú", selected: false },
    { id: "4", name: "Marcelia", bank: "Nu Bank", selected: false },
    { id: "5", name: "Marcelia", bank: "Caixa", selected: false },
    { id: "6", name: "Cicero", bank: "Itaú", selected: false },
    { id: "7", name: "Cicero", bank: "BB", selected: false },
    { id: "8", name: "Cicero", bank: "Nu bank", selected: false },
    { id: "9", name: "Cicero", bank: "Pic pay", selected: false },
    { id: "10", name: "Cicero", bank: "Neo", selected: false },
    { id: "11", name: "Cicero", bank: "C6", selected: false },
    { id: "12", name: "Cicero", bank: "Pag bank", selected: false },
    { id: "13", name: "Cicero", bank: "Caixa", selected: false },
    { id: "14", name: "Cicero", bank: "inter", selected: false },
    { id: "15", name: "Cicero", bank: "Mercado Pago", selected: false },
    { id: "16", name: "Roberto", bank: "Nu bank", selected: false },
    { id: "17", name: "Tamires", bank: "Nu bank", selected: false },
    { id: "18", name: "Tairine", bank: "Nu bank", selected: false },
    { id: "19", name: "Cláudio", bank: "Nu bank", selected: false },
    { id: "20", name: "Milton", bank: "Caixa", selected: false },
];